#!/usr/bin/env bash
# Generate _data/gallery.yml from thumb image dimensions
# Usage: bash photos/generate_gallery.sh
# Requires: sips (macOS), awk

set -euo pipefail

THUMB_DIR="photos/static/gallery/thumb"
OUTPUT="_data/gallery.yml"

mkdir -p _data

echo "# Auto-generated by photos/generate_gallery.sh" > "$OUTPUT"

for f in $(ls "$THUMB_DIR"/*.jpg | sed 's/.*\///' | sed 's/\.jpg//' | sort -n); do
  img="$THUMB_DIR/$f.jpg"
  w=$(sips -g pixelWidth "$img" 2>/dev/null | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$img" 2>/dev/null | awk '/pixelHeight/{print $2}')
  ar=$(awk "BEGIN{printf \"%.3f\", $w/$h}")
  echo "- file: $f"   >> "$OUTPUT"
  echo "  w: $w"       >> "$OUTPUT"
  echo "  h: $h"       >> "$OUTPUT"
  echo "  ar: $ar"     >> "$OUTPUT"
done

echo "Generated $OUTPUT with $(grep -c '^- file:' "$OUTPUT") entries"
