title: Fermin Silva
description: Software engineer
url: "https://fermin-silva.github.io"
baseurl: ""

collections:
  routines:
    output: true
    permalink: /rutina/routines/:slug/

defaults:
  - scope: { path: "", type: routines }
    values: { layout: rutina-routine }

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude: [Gemfile, Gemfile.lock, README.md]
